spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/ra
      username: matthew633jdi
      password: ianpapa0324
      driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect

decorator:
  datasource:
    p6spy:
      enable-logging: true
logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace